services:

  firesync:
    build:
      context: ..
      dockerfile: dev/Dockerfile
      args:
        BUILD_PATH: ./cmd/firesync
    develop:
      watch:
        - action: rebuild
          path: ../
          include: './internal/**/*.go'
    environment:
      PUBSUB_EMULATOR_HOST: pubsub:8080
      FIRESTORE_EMULATOR_HOST: firestore:8080
      ENVIRONMENT: local

      # OpenTelemetry configuration for Uptrace
      OTEL_EXPORTER_OTLP_ENDPOINT: http://uptrace:4317
      OTEL_EXPORTER_OTLP_INSECURE: "true"
      OTEL_EXPORTER_OTLP_HEADERS: uptrace-dsn=http://firesync_secret@localhost:8080?grpc=4317
      OTEL_EXPORTER_OTLP_COMPRESSION: gzip
      OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION: BASE2_EXPONENTIAL_BUCKET_HISTOGRAM
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: DELTA
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: no
